import { Link } from "react-router-dom";

const EFFECTIVE = "1 January 2025";
const EMAIL = "legal@refrll.com";

function LegalLayout({ title, subtitle, children }) {
  return (
    <div className="min-h-screen bg-surface">
      <nav className="border-b border-default bg-white/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link to="/"><img src="/logo.png" alt="Refrll" className="h-9 w-auto" /></Link>
          <div className="flex items-center gap-4 text-sm">
            <Link to="/terms"   className="text-ink-muted hover:text-ink transition-colors">Terms</Link>
            <Link to="/privacy" className="text-ink-muted hover:text-ink transition-colors">Privacy</Link>
            <Link to="/cookies" className="text-ink-muted hover:text-ink transition-colors">Cookies</Link>
          </div>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <div className="mb-10">
          <p className="text-xs font-semibold text-accent uppercase tracking-widest mb-3">Legal</p>
          <h1 className="font-display text-4xl font-bold text-ink mb-3">{title}</h1>
          <p className="text-ink-muted">{subtitle}</p>
          <div className="mt-4 inline-flex items-center gap-2 bg-surface-alt border border-default text-xs text-ink-muted px-3 py-1.5 rounded-full">
            📅 Effective: {EFFECTIVE}
          </div>
        </div>
        <div className="space-y-10 text-sm text-ink-muted leading-relaxed">{children}</div>
        <div className="mt-12 border-t border-default pt-8 flex flex-wrap gap-4 text-xs text-ink-faint">
          <Link to="/terms"   className="hover:text-ink transition-colors">Terms & Conditions</Link>
          <Link to="/privacy" className="hover:text-ink transition-colors">Privacy Policy</Link>
          <Link to="/cookies" className="hover:text-ink transition-colors">Cookie Policy</Link>
          <a href={`mailto:${EMAIL}`} className="hover:text-ink transition-colors">{EMAIL}</a>
          <Link to="/" className="ml-auto hover:text-ink transition-colors">← Back to Refrll</Link>
        </div>
      </div>
    </div>
  );
}

function S({ title, children }) {
  return (
    <section>
      <h2 className="font-display text-lg font-bold text-ink mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function Table({ rows }) {
  return (
    <div className="overflow-x-auto rounded-xl border border-default">
      <table className="w-full text-xs">
        <thead className="bg-surface-alt">
          <tr>
            {rows[0].map((h, i) => <th key={i} className="text-left px-4 py-2.5 font-semibold text-ink">{h}</th>)}
          </tr>
        </thead>
        <tbody className="divide-y divide-default">
          {rows.slice(1).map((row, i) => (
            <tr key={i} className="bg-white">
              {row.map((cell, j) => <td key={j} className="px-4 py-2.5 text-ink-muted">{cell}</td>)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy Policy"
      subtitle="We take your privacy seriously. This policy explains what data we collect, why we collect it, how we use it, and your rights over it."
    >
      <S title="1. Who We Are">
        <p>
          Refrll ("we", "us", "our") operates the platform at refrll.com. We are the data controller responsible for your personal data. For any privacy-related queries, contact our team at <a href={`mailto:${EMAIL}`} className="text-accent hover:underline">{EMAIL}</a>.
        </p>
      </S>

      <S title="2. Data We Collect">
        <p>We collect the following categories of personal data when you use Refrll:</p>
        <Table rows={[
          ["Category", "Examples", "How Collected"],
          ["Identity data", "Full name, display alias", "Provided by you on registration or profile"],
          ["Contact data", "Email address", "Provided by you on registration"],
          ["Professional data", "Current employer, job title, skills, years of experience, LinkedIn URL", "Provided by you on profile"],
          ["Resume / CV", "PDF document containing your professional history", "Uploaded by you"],
          ["Usage data", "Pages visited, features used, timestamps, IP address, browser type", "Collected automatically"],
          ["Communication data", "Application messages, referral request notes", "Provided by you"],
          ["Referral activity", "Applications submitted, referrals made, status updates", "Generated by platform activity"],
        ]} />
        <p>
          We do not collect sensitive personal data such as caste, religion, biometric data, health information, or financial account details (other than payment transaction references if Pro features are used).
        </p>
      </S>

      <S title="3. How We Use Your Data">
        <Table rows={[
          ["Purpose", "Legal Basis"],
          ["Creating and managing your account", "Contract performance"],
          ["Matching seekers to referrers", "Contract performance"],
          ["Sending application status notifications by email and in-app", "Contract performance / Legitimate interests"],
          ["Displaying your name or alias on the public leaderboard (referrers only, opt-in)", "Consent"],
          ["Sending verification and transactional emails", "Contract performance"],
          ["Analysing platform usage to improve the service", "Legitimate interests"],
          ["Fraud prevention and security", "Legitimate interests / Legal obligation"],
          ["Complying with legal obligations", "Legal obligation"],
        ]} />
      </S>

      <S title="4. Leaderboard & Anonymity">
        <p>
          Referrers appear on the public leaderboard. <strong>By default, your real name is never shown.</strong> We automatically display a privacy-preserving alias (e.g., "R. Kumar") unless you explicitly opt in to showing your real name in your Privacy Settings.
        </p>
        <p>
          You can also set a custom display alias (e.g., "Priya M." or any chosen name) in your profile. This alias is the only information visible to the public. Your email, employer, and full name are never shared publicly without your explicit consent.
        </p>
        <p>
          Seekers' names are never displayed on any public-facing page. Seeker data (including resumes) is shared only with the specific Referrer assigned to their application and with no one else.
        </p>
      </S>

      <S title="5. Data Sharing">
        <p>We share your personal data only in the following circumstances:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>With assigned Referrers:</strong> When you submit a referral application as a Seeker, your name, email, resume, skills, bio, and application message are shared with the Referrer assigned to your request.</li>
          <li><strong>With Seekers:</strong> When you are assigned a referral request as a Referrer, the Seeker's application details are shared with you.</li>
          <li><strong>Service providers:</strong> We use trusted third-party services to operate the Platform, including cloud hosting (MongoDB Atlas), file storage (Cloudinary), and email delivery (Resend). These providers process data on our behalf under strict data processing agreements.</li>
          <li><strong>Legal requirements:</strong> We may disclose your data if required by law, court order, or regulatory authority.</li>
          <li><strong>Business transfers:</strong> If Refrll is acquired or merges with another entity, your data may be transferred as part of that transaction. We will notify you beforehand.</li>
        </ul>
        <p>We do not sell, rent, or trade your personal data to any third party for marketing purposes.</p>
      </S>

      <S title="6. Resume Data">
        <p>
          Your resume is stored securely on Cloudinary, a third-party cloud storage provider. It is accessible only to you and to Referrers assigned to your applications. We do not use your resume for any purpose other than facilitating the referral process.
        </p>
        <p>
          We recommend not including sensitive personal identifiers (such as Aadhaar number, PAN, or passport details) in your uploaded resume.
        </p>
      </S>

      <S title="7. Data Retention">
        <Table rows={[
          ["Data Type", "Retention Period"],
          ["Account and profile data", "Until account deletion, then 30 days before permanent erasure"],
          ["Application history", "3 years from the date of application"],
          ["Resume files", "Until you delete them or your account is closed"],
          ["Email notifications", "Not retained by Refrll after delivery"],
          ["Usage / analytics logs", "12 months"],
        ]} />
        <p>
          After the relevant retention period, data is securely deleted or anonymised such that it can no longer be linked to you.
        </p>
      </S>

      <S title="8. Your Rights">
        <p>Under applicable Indian data protection law and general best practice, you have the following rights:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Access:</strong> Request a copy of the personal data we hold about you.</li>
          <li><strong>Correction:</strong> Request correction of inaccurate or incomplete data.</li>
          <li><strong>Erasure:</strong> Request deletion of your account and personal data ("right to be forgotten"), subject to legal retention obligations.</li>
          <li><strong>Portability:</strong> Request your data in a structured, machine-readable format.</li>
          <li><strong>Withdrawal of consent:</strong> Where processing is based on consent (e.g., leaderboard display), you can withdraw consent at any time in your Privacy Settings.</li>
          <li><strong>Objection:</strong> Object to processing based on legitimate interests.</li>
        </ul>
        <p>
          To exercise any of these rights, email us at <a href={`mailto:${EMAIL}`} className="text-accent hover:underline">{EMAIL}</a>. We will respond within 30 days. We may need to verify your identity before fulfilling a request.
        </p>
      </S>

      <S title="9. Security">
        <p>
          We implement appropriate technical and organisational measures to protect your personal data against unauthorised access, alteration, disclosure, or destruction. These include encrypted data transmission (HTTPS/TLS), hashed password storage, HTTP-only authentication cookies, and access controls.
        </p>
        <p>
          No method of transmission over the internet is 100% secure. While we strive to use commercially acceptable means to protect your data, we cannot guarantee absolute security. In the event of a data breach that affects your rights, we will notify you as required by law.
        </p>
      </S>

      <S title="10. Cookies">
        <p>
          We use cookies and similar tracking technologies to operate the Platform. Please see our <Link to="/cookies" className="text-accent hover:underline">Cookie Policy</Link> for full details on what cookies we use and how to manage them.
        </p>
      </S>

      <S title="11. Children's Privacy">
        <p>
          Refrll is not directed at or intended for use by individuals under the age of 18. We do not knowingly collect personal data from minors. If we become aware that we have inadvertently collected data from a minor, we will promptly delete it. If you believe we have collected data from a minor, contact us at {EMAIL}.
        </p>
      </S>

      <S title="12. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. We will notify you of material changes via email or in-app notification at least 7 days before they take effect. The effective date at the top of this page will always reflect the most recent version.
        </p>
      </S>

      <S title="13. Contact & Grievances">
        <p>For any questions, concerns, or grievances regarding this Privacy Policy or your data:</p>
        <div className="bg-surface-alt rounded-xl p-4 space-y-1">
          <p className="font-semibold text-ink">Refrll Privacy Team</p>
          <p>Email: <a href={`mailto:${EMAIL}`} className="text-accent hover:underline">{EMAIL}</a></p>
          <p>Response time: within 30 business days</p>
        </div>
      </S>
    </LegalLayout>
  );
}
